# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from main import MainWindow2

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(784, 605)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        MainWindow.setStyleSheet("QMainWindow {\n"
                                 "        background-color: \'#8bbdd9\';\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
                                         "        background-color: \'#8bbdd9\';\n"
                                         "}")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 0, 361, 301))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 320, 121, 31))
        self.label_2.setStyleSheet("QLabel{\n"
                                   "        font-size: 25px;\n"
                                   "        color: \'white\';\n"
                                   "}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 410, 111, 20))
        self.label_3.setStyleSheet("QLabel{\n"
                                   "        font-size: 25px;\n"
                                   "        color: \'white\';\n"
                                   "}")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(350, 320, 191, 51))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
                                    "        border: 4px solid \'white\';\n"
                                    "        font-size: 20px;\n"
                                    "        color: \'white\';\n"
                                    "        background-color: \'#298fca\';\n"
                                    "        padding: 10px;\n"
                                    "\n"
                                    "}\n"
                                    "")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(350, 390, 191, 51))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
                                      "        border: 4px solid \'white\';\n"
                                      "        font-size: 20px;\n"
                                      "        color: \'white\';\n"
                                      "        background-color: \'#298fca\';\n"
                                      "        padding: 10px;\n"
                                      "\n"
                                      "}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 270, 71, 91))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("user.png"))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 360, 81, 81))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("password.png"))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(450, 450, 101, 20))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 480, 151, 71))
        self.pushButton.setStyleSheet("QPushButton{\n"
                                      "        border-radius : 30;\n"
                                      "        border: 6px solid \'#0079bf\';\n"
                                      "        border-style: double;\n"
                                      "        font-size: 20px;\n"
                                      "        color: \'white\';\n"
                                      "}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("back.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 480, 151, 71))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
                                        "        border-radius : 30;\n"
                                        "        border: 6px solid \'#0079bf\';\n"
                                        "        border-style: double;\n"
                                        "        font-size: 20px;\n"
                                        "        color: \'white\';\n"
                                        "}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("login.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 784, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Username"))
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.lineEdit.setPlaceholderText(
            _translate("MainWindow", "enter username"))
        self.lineEdit_2.setPlaceholderText(
            _translate("MainWindow", "enter password"))
        self.label_6.setText(_translate("MainWindow", "Forgot password?"))
        self.pushButton.setText(_translate("MainWindow", "Back"))
        self.pushButton_2.setText(_translate("MainWindow", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
