# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'live_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(696, 573)
        self.TEXT = QtWidgets.QTextBrowser(Dialog)
        self.TEXT.setGeometry(QtCore.QRect(150, 350, 391, 51))
        self.TEXT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TEXT.setObjectName("TEXT")
        self.STOP = QtWidgets.QPushButton(Dialog)
        self.STOP.setGeometry(QtCore.QRect(350, 410, 200, 60))
        self.STOP.setMinimumSize(QtCore.QSize(200, 60))
        self.STOP.setMaximumSize(QtCore.QSize(200, 60))
        self.STOP.setStyleSheet("QPushButton{\n"
"        border-radius : 30;\n"
"        border: 6px solid \'#0079bf\';\n"
"        border-style: double;\n"
"        font-size: 20px;\n"
"        color: \'white\';\n"
"}")
        self.STOP.setObjectName("STOP")
        self.imgLabel = QtWidgets.QLabel(Dialog)
        self.imgLabel.setGeometry(QtCore.QRect(110, 30, 491, 311))
        self.imgLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.imgLabel.setText("")
        self.imgLabel.setObjectName("imgLabel")
        self.START = QtWidgets.QPushButton(Dialog)
        self.START.setGeometry(QtCore.QRect(150, 410, 200, 60))
        self.START.setMinimumSize(QtCore.QSize(200, 60))
        self.START.setMaximumSize(QtCore.QSize(200, 60))
        self.START.setStyleSheet("QPushButton{\n"
"        border-radius : 30;\n"
"        border: 6px solid \'#0079bf\';\n"
"        border-style: double;\n"
"        font-size: 20px;\n"
"        color: \'black\';\n"
"}")
        self.START.setObjectName("START")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.STOP.setText(_translate("Dialog", "Stop"))
        self.START.setText(_translate("Dialog", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
